export const SELECT_PRODUCT = 'SELECT_PRODUCT'
export const PLUS_PRODUCT = 'PLUS_PRODUCT'
export const MINUS_PRODUCT = 'MINUS_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const COUNT_PRICE_PRODUCTS = 'COUNT_PRICE'